---
title: "flexdashboard + shiny_prerendered"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(dplyr)
library(DT)
library(plotly)
blotter_data <- read.csv("Blotter_Data_Archive.csv", header = T) %>% sample_frac(., 0.2)
blotter_data$INCIDENTTIME <- strptime(x = as.character(blotter_data$INCIDENTTIME),
                                      format = "%Y-%m-%dT%H:%M:%S") #From factor to datetime
blotter_data$time <- format(blotter_data$INCIDENTTIME, "%H:%M:%S") #From datetime to character
blotter_data$time <- as.POSIXct(x = blotter_data$time, format = "%H:%M:%S") #From character to continuous time var
blotter_data$date <- format(blotter_data$INCIDENTTIME, "%m-%d")
blotter_data$date <- as.POSIXct(x = blotter_data$date, format = "%m-%d")
blotter_data$type <- cut(blotter_data$HIERARCHY, c(-Inf, 9, 98, Inf), labels = c("Type 1 - Major Crime", "Type 2 - Minor Crime", "No Data or None"))
blotter_data$INCIDENTTIME <- as.POSIXct(blotter_data$INCIDENTTIME) #to avoid POSIXlt error
neighborhoods <- sort(unique(blotter_data$INCIDENTNEIGHBORHOOD))
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
#City council district input
 checkboxGroupInput(inputId = "selected_districts",
                    label = "Select Council District(s)",
                    choices = c(1:9),
                    selected = c(1:9)
)

#date range input
dateRangeInput(inputId = "date_range",
               label = "Date Range: yyyy-mm-dd",
               start = "2009-01-01",
               end = "2019-01-01",
               startview = "year")

#Hierarchy level input
checkboxGroupInput(inputId = "selected_hierarchy",
                   label = "Select Crime Severity",
                   choices = levels(blotter_data$type),
                   selected = levels(blotter_data$type))
```

Outputs {.tabset}
-----------------------------------------------------------------------

### Time of Day

```{r context="server"}
blotter_subset <- reactive({
  req(input$selected_districts, input$date_range, input$selected_hierarchy)
  filter(blotter_data, COUNCIL_DISTRICT %in% input$selected_districts & 
           between(INCIDENTTIME, as.POSIXct(input$date_range[[1]]), as.POSIXct(input$date_range[[2]])) &
           type %in% input$selected_hierarchy)
})

output$time <- renderPlotly({
  (ggplot(blotter_subset(), aes(x = blotter_subset()$time)) + geom_freqpoly(stat = "bin", binwidth = 3600) +
    geom_freqpoly(stat = "bin", binwidth = 3600, aes(color = type)) +
    scale_x_datetime(date_label = "%H:%M") +
    labs(x = "Time of Day", y = "Count", title = "Count of Police Blotter Incidents by Time of Day")) %>%
  ggplotly(tooltip = c("y", "type"))
})
```

```{r context="render"}
plotlyOutput("time")
```


### Time of Year

```{r context="server"}
output$date <- renderPlotly({
  (ggplot(blotter_subset(), aes(x = blotter_subset()$date, fill = type)) + 
    geom_histogram(stat = "bin", bins = 12) +
    scale_x_datetime(date_label = "%m") +
    labs(x = "Time of Year", y = "Count", title = "Count of Police Blotter Incidents by Time of Year and Type")) %>%
  ggplotly(tooltip = c("y", "type"))
})
```

```{r context="render"}
plotlyOutput("date")
```


### Cleared Status

```{r context="server"}
output$flag <- renderPlotly({
  (ggplot(blotter_subset(), aes(x = type, fill = CLEAREDFLAG)) +
      geom_bar() +
      labs(x = "Crime Hierarchy Type", y = "Count", Title = "Cleared Status by Hierarchy Type")) %>%
  ggplotly()
})
```

```{r context="render"}
plotlyOutput("flag")
```

Row 
-----------------------------------------------------------------------

### Cleared Rate

```{r context="server"}
output$clear <- renderGauge({
  rate <- ((nrow(filter(blotter_subset(), CLEAREDFLAG == "Y"))/nrow(blotter_subset())) * 100) %>% signif(2)
  gauge(rate, min = 0, max = 100, symbol = '%')
})
```

```{r context="render"}
gaugeOutput(outputId = "clear")
```

### Most Common Incident

```{r context="server"}
output$dist <- renderValueBox({
  dist <- sort(blotter_subset()$INCIDENTHIERARCHYDESC,decreasing=TRUE)[1]
  valueBox(dist)
})
```

```{r context="render"}
valueBoxOutput(outputId = "dist")
```

### Highest-Incident Neighborhood

```{r context="server"}
output$neigh <- renderValueBox({
  neigh <- sort(blotter_subset()$INCIDENTNEIGHBORHOOD,decreasing=TRUE)[1]
  valueBox(neigh, color = "orange")
})
```

```{r context="render"}
valueBoxOutput(outputId = "neigh")
```

Row 
-----------------------------------------------------------------------

### Data

```{r context="server"}
output$DT <- renderDataTable({
  blotter_subset()
})
```

```{r context="render"}
dataTableOutput(outputId = "DT")
```